source = ~/.config/hypr/conf/colors.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/bindings.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/monitors.conf

exec-once = /usr/libexec/lxqt-policykit-agent
exec-once = ags run ~/.config/ags/app.ts
exec-once = bash -c 'if [ -f "$backgroundmp4" ]; then mpvpaper -o "no-audio loop --panscan=0.65 --video-align-y=1" "*" "$backgroundmp4"; else hyprpaper & sleep 0.5 && hyprctl hyprpaper preload "$background" && hyprctl hyprpaper wallpaper ",$background"; fi'