source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/bindings.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/monitors.conf

exec-once = ags run ~/.config/ags/app.ts
exec-once = mpvpaper -o "no-audio loop --panscan=0.65 --video-align-y=1" "*" /home/emerson/Imágenes/Wallpapers/rei.mp4
