##################################################
################## GENERAL #######################
##################################################

general {
    layout = master
    border_size = 1

    col.active_border = rgba(444444ff) rgba(d3d3d3ff) 45deg
    col.inactive_border = rgba(444444ff)

    gaps_in = 0
    gaps_out = 1

    # Permitir cambiar el tamaño arrastrando los bordes
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true
}

# Smart gaps (no gaps when only one window or fullscreen)
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

##################################################
################## MASTER ########################
##################################################

master {
    new_status = master
    mfact = 0.55
}
